Class_based_view/advanced_cbv/advanced_cbv/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from basic_app import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view()),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app'))
]

Class_based_view/advanced_cbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    # url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='Delete'),
]

# the pk is coming from the school_list.html in school.id, here we are linking to that particular school.

Class_based_view/advanced_cbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):   # Here we are telling what primary key the school returned with.
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

Class_based_view/advanced_cbv/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from . import models


class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # Every details of list is saved because of ListView
    # Here the ListView is creating a school list and naming it school_list. In the school_list school is coming from
    # the .School, the ListView is lowering case of .School and renaming it as school_list which can be called in
    # school_list.html in for loop or for other manipulations.
    # Or if we want to change the default name then use context_object_name = "changed name" and this name can be
    # called in the school_list.html for further manipulation.


class SchoolDetailView(DetailView):    # Detail view returns model in the lower case.
    context_object_name = 'schools_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principle', 'location')    # Here creating the fields given in the parenthesis
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principle')    # Here we are updating name and principle of the school.
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

Class_based_view/advanced_cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Base</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
            <li><a href="#"></a></li>

        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

Class_based_view/advanced_cbv/basic_app/templates/basic_app/school_conform_delete.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

Class_based_view/advanced_cbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the school Detail Page</h1>
    <h2>School details:</h2>
    <p>Name: {{schools_detail.name}}</p>
    <p>Principle: {{schools_detail.principle }}</p>
    <p>Location: {{schools_detail.location }}</p>
    <h3>Students: </h3>
    {% for student in schools_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

Class_based_view/advanced_cbv/basic_app/templates/basic_app/school_form.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

    <h1>
        {% if not form.instance.pk %}   <!---the heading of the form page is going to check if the instance of the
        primary key exists or not and if it does not exist it is going to Create School (creating the new school)
        otherwise update the school --->
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

{% endblock %}

Class_based_view/advanced_cbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Welcome to a list of all the schools!</h1>
    <ol>
        {% for school in schools %}
        <!--When someone comes to  school list page and clicks on school name in that list view href returns the single
        number that corresponds to primary key or pk-->
            <h2><li><a href={{school.id}}>{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>

{% endblock %}

Class_based_view/advanced_cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Base</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
            <li><a href="#}"></a></li>

        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

Class_based_view/advanced_cbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}